name: "Test Decoders"
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'internal/decoders/**'
  push:
    branches:
      - 'main'

jobs:
  test_decoders:
    name: "test decoders"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      - name: Test
        run: go test -cover -coverprofile=decoders_coverage.txt ./internal/decoders/...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: decoders-code-coverage
          path: decoders_coverage.txt
